email: gmarantef@hotmail.com

features:
  - brew
  - bundle
  - cloud
  - containers
  - gui
  - security
  - shell
  - ai

context: personal

default_shell: zsh

ai_agents:
  - claude_code

cloud_providers:
  - aws

vscode_extensions:
  - ms-azuretools.vscode-docker
  - ms-azuretools.vscode-containers
  - eamodio.gitlens
  - redhat.vscode-yaml
  - timonwong.shellcheck
  - mutantdino.resourcemonitor

secrets:
  aws:
    personal: aws-credentials-personal
    work: aws-credentials-work