email: gmarantef@hotmail.com

features:
  - brew
  - bundle
  - cloud
  - containers
  - gui
  - security
  - shell
  - ai

context: personal

default_shell: zsh

ai_agents:
  - claude_code

cloud_providers: [aws]

secrets:
  aws:
    personal: aws-credentials-personal
    work: aws-credentials-work